project:
  type: website
  render:
    - "*.qmd"
    - "!slides/"

execute:
  freeze: auto

website:
  title: "Quantitative Methods in Psychology"
  description: "An intensive introduction to statistical reasoning in psychological research"
  site-url: "https://seredes.github.io/quant-methods-psych"

  page-navigation: true

  navbar:
    pinned: true
    background: "#CF4446"
    right:
      - syllabus.qmd
      - schedule.qmd
      - text: "Content"
        file: content/01-content.qmd
      - text: "Assignments"
        file: assignment/index.qmd
      - text: "Resources"
        file: resource/index.qmd

  sidebar:
    - title: "Content"
      style: "docked"
      search: false
      background: light
      contents:
        - text: "Lecture 1"
          file: content/01-content.qmd
        - text: "Lecture 2"
          file: content/02-content.qmd
        - text: "Lecture 3"
          file: content/03-content.qmd
        - text: "Lecture 4"
          file: content/04-content.qmd
        - text: "Lecture 5"
          file: content/05-content.qmd
        - text: "Lecture 6"
          file: content/06-content.qmd
        - text: "Lecture 7"
          file: content/07-content.qmd
        - text: "Lecture 8"
          file: content/08-content.qmd
        - text: "Lecture 9"
          file: content/09-content.qmd
        - text: "Lecture 10"
          file: content/10-content.qmd
        - text: "Lecture 11"
          file: content/11-content.qmd
        - text: "Lecture 12"
          file: content/12-content.qmd
        - text: "Lecture 13"
          file: content/13-content.qmd
        - text: "Lecture 14"
          file: content/14-content.qmd
        - text: "Lecture 15"
          file: content/15-content.qmd
        - text: "Lecture 16"
          file: content/16-content.qmd
        - text: "Lecture 17"
          file: content/17-content.qmd
        - text: "Lecture 18"
          file: content/18-content.qmd
        - text: "Lecture 19"
          file: content/19-content.qmd
        - text: "Lecture 20"
          file: content/20-content.qmd

    - title: "Assignments"
      contents:
        - section: "Overview"
          contents:
            - assignment/index.qmd
        - section: "Homework"
          contents:
            - text: "Homework 1"
              file: assignment/01-homework.qmd
            - text: "Homework 2"
              file: assignment/02-homework.qmd
            - text: "Homework 3"
              file: assignment/03-homework.qmd
            - text: "Homework 4"
              file: assignment/04-homework.qmd
            - text: "Homework 5"
              file: assignment/05-homework.qmd
            - text: "Homework 6"
              file: assignment/06-homework.qmd
            - text: "Homework 7"
              file: assignment/07-homework.qmd
            - text: "Homework 8"
              file: assignment/08-homework.qmd
            - text: "Homework 9"
              file: assignment/09-homework.qmd
        - section: "Exams"
          contents:
            - text: "Midterm"
              file: assignment/midterm.qmd
            - text: "Final"
              file: assignment/final.qmd

    - title: "Resources"
      contents:
        - section: "Resources"
          contents:
            - resource/index.qmd
            - resource/r-basics.qmd
            - resource/style-guide.qmd

  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}})
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: true
